-- MySQL Script generated by MySQL Workbench
-- Fri Feb 26 22:24:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Secretaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Secretaire` (
  `idSec` INT NOT NULL AUTO_INCREMENT,
  `mailSec` VARCHAR(45) NOT NULL,
  `passSec` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSec`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Patient` (
  `idPat` INT NOT NULL AUTO_INCREMENT,
  `nomPat` VARCHAR(45) NOT NULL,
  `prenomPat` VARCHAR(45) NOT NULL,
  `cinPat` VARCHAR(45) NULL DEFAULT 'none',
  `adressPat` VARCHAR(45) NULL,
  `telPat` VARCHAR(45) NULL DEFAULT 'none',
  `dateNPat` DATE NULL,
  `Secretaire_idSec` INT NOT NULL,
  PRIMARY KEY (`idPat`, `Secretaire_idSec`),
  INDEX `fk_Patient_Secretaire1_idx` (`Secretaire_idSec` ASC) VISIBLE,
  CONSTRAINT `fk_Patient_Secretaire1`
    FOREIGN KEY (`Secretaire_idSec`)
    REFERENCES `mydb`.`Secretaire` (`idSec`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RDV`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RDV` (
  `idRDV` INT NOT NULL AUTO_INCREMENT,
  `datetimeRDV` DATE NULL,
  `idPat` INT NULL,
  `Secretaire_idSec` INT NOT NULL,
  PRIMARY KEY (`idRDV`, `Secretaire_idSec`),
  INDEX `fk_idpat_idx` (`idPat` ASC) VISIBLE,
  INDEX `fk_RDV_Secretaire1_idx` (`Secretaire_idSec` ASC) VISIBLE,
  CONSTRAINT `fk_idpat`
    FOREIGN KEY (`idPat`)
    REFERENCES `mydb`.`Patient` (`idPat`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_RDV_Secretaire1`
    FOREIGN KEY (`Secretaire_idSec`)
    REFERENCES `mydb`.`Secretaire` (`idSec`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
